// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zodtjrtsacnwohcthopx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZHRqcnRzYWNud29oY3Rob3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDI2NzYsImV4cCI6MjA2OTExODY3Nn0.lvDIHLvO1b_Kt95VYAg7NSzSACgHzqazpq-h2y3Fi9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});